name: Build and Test

on: [push, pull_request]
jobs:
  run-msbuild-vstest:
    runs-on: windows-latest
    name: Run MSBuild and VSTest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.1
        id: setup_msbuild
      
      - name: Build app for release
        run: msbuild src\YourProjectFile.csproj -t:rebuild -verbosity:diag -property:Configuration=Release